version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
