services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
      - NEXT_PUBLIC_TEST_ENV=${TEST_ENV}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/app
    command: npm run dev
