version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      args:
        - MONGODB_USERNAME=${MONGODB_USERNAME}
        - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        - MONGODB_DB_NAME=${MONGODB_DB_NAME}
        - NEXT_PUBLIC_API_URL=${API_URL}
        - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
        - API_URL_SERVER=${API_URL_SERVER}
        - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    environment:
      - NODE_ENV=production
   
  backend:
    build:
      dockerfile: Dockerfile.prod
