# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy the rest of the app's code
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Start the app in production mode
CMD ["npm", "run", "start"]
