import type {Metadata} from "next";
import {Lexend, Merriweather} from "next/font/google";
// The following import prevents a Font Awesome icon server-side rendering bug,
// where the icons flash from a very large icon down to a properly sized one:
import "@fortawesome/fontawesome-svg-core/styles.css";
// Prevent fontawesome from adding its CSS since we did it manually above:
import {config} from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; /* eslint-disable import/first */
import "../globals.css";
import Sidebar from "@/components/carrier/sidebar";
import TopNav from "@/components/carrier/topbar";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  weight: ["300", "400", "500", "600", "700"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CarrierLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lexend.variable} ${merriweather.variable} antialiased flex`}
      >
        <Sidebar />
        <div className="flex flex-col w-full font-lexend h-screen">
          <TopNav />
          {children}
        </div>
      </body>
    </html>
  );
}
